### ISSUE TITLE
Missing www alias 

### ISSUE THREAD

**Issue by KingFruit85** [NorfolkDev/nordevcon-website#101]
When trying to navigate to `https://www.nordevcon.com/` the browser returns the following error message:

```
404: NOT_FOUND
Code: DEPLOYMENT_NOT_FOUND
ID: lhr1::kcff4-1659891123345-650a64def99e
```

navigating to `https://nordevcon.com/ `resolves just fine

**Comment by Illizian** [comment]
Thanks @KingFruit85, I think I've resolved this with a new CloudFlare Page Rule but it might still be subject to DNS propagation.

Working here, but we'll wait a few and test

**Comment by KingFruit85** [comment]
> Thanks @KingFruit85, I think I've resolved this with a new CloudFlare Page Rule but it might still be subject to DNS propagation.
> 
> Working here, but we'll wait a few and test

Just checked, www is working now 👍

**Comment by KingFruit85** [comment]
Just checked, www is working now. Rapid stuff.
