### ISSUE TITLE
Mapbox map not loading

### ISSUE THREAD

**Issue by kevsturman** [NorfolkDev/nordevcon-website#71]
Image load is failing because the access token is not being provided.

[MapboxStaticMap.jsx](https://github.com/NorfolkDev/nordevcon-website/blob/5347baf444911865433d2ec4260f4fef7aad787b/components/MapboxStaticMap.jsx#L1)

```js
const apiKey = process.env.MAPBOX_API_KEY;
```

Is the env variable being set properly in vercel? or Should it be `NEXT_PUBLIC_MAPBOX_API_KEY`?

**Comment by shaunchurch** [comment]
Thanks @kevsturman, that's exactly right. Fixed. :)
